import React, { useState } from "react";
import "@/styles/post.css";
import apiService from "@/utils/ApiService";
import { useAuth } from "@/contexts/AuthProvider";
import useSWR from "swr";
import { fetcher } from "@/utils/fetcher";
import { RxAvatar } from "react-icons/rx";
import Link from "next/link";
import LetterPicture from "@/components/LetterPicture";
import ButtonWithIcon from "@/components/Buttons/buttonWithIcon";
import { FiArrowDown, FiArrowUp } from "react-icons/fi";
import cn from "@/utils/cn";
import { useRouter } from "next/navigation";

const Comments = ({
  postId,
  authorId,
}: {
  postId: string;
  authorId: string;
}) => {
  const { data } = useSWR(`/posts/${postId}/comments`, (url) => fetcher(url));

  return (
    <div className="w-full mt-9">
      <ul>
        {data?.comments?.map((comment: any) => (
          <CommentItem
            key={comment.id}
            comment={comment}
            authorId={authorId}
            isRoot={true}
          />
        ))}
      </ul>
    </div>
  );
};

const CommentItem = ({ comment, authorId, isRoot }: any) => {
  const [currentVote, setCurrentVote] = useState<number>(0); // État du vote actuel
  const initialScore = typeof comment.votes === "number" ? comment.votes : 0; // Score initial du commentaire
  const [score, setScore] = useState<number>(initialScore);
  const router = useRouter();

  const handleUpVote = () => {
    if (currentVote !== 1) {
      setCurrentVote(1);
      setScore(score + 1);
    }
  };

  const handleDownVote = () => {
    if (currentVote !== -1) {
      setCurrentVote(-1);
      setScore(score - 1);
    }
  };

  const onAuthorProfile = () => {
    router.push(`/profile/${comment?.author?.username}`);
  };

  return (
    <div
      className={cn(
        "px-4 py-4 my-4 bg-[#fcfcfc]",
        comment?.isAI
          ? ["bg-[#F8F9FD]", isRoot && "border-blue-400 border"]
          : "",
      )}
    >
      <li key={comment.id}>
        <div className="flex">
          {comment?.isAI ? (
            <>
              <div className={`rounded-full bg-primary h-8 w-8`}>
                <img
                  src="/images/ai-avatar.png"
                  alt="ai"
                  className="h-8 w-8 rounded-full"
                />
              </div>
            </>
          ) : (
            <LetterPicture
              username={comment?.author?.username || "Inconnu"}
              height={100}
              width={100}
              fontSize={32}
              style={{
                height: "24px",
                width: "24px",
              }}
            />
          )}
          <div
            className={cn(
              "comment-content text-blue-400  ml-2",
              !comment?.isAI && "cursor-pointer text-primary",
            )}
            onClick={comment?.isAI ? () => {} : onAuthorProfile}
          >
            {comment?.isAI ? "BuddyAI" : comment?.author?.username || "Inconnu"}
          </div>
          {comment?.author?.id === authorId && (
            <RxAvatar size={18} className="ml-1 mt-1" />
          )}
          {comment?.isAI && (
            <div className="ml-2 bg-blue-400 px-2 font-bold rounded flex items-center h-5">
              <span className="text-xs text-white">AI</span>
            </div>
          )}
        </div>
        <div className="mt-5 flex">
          <div className="flex flex-col text-zinc-400 w-0">
            <ButtonWithIcon
              onClick={handleUpVote}
              icon={FiArrowUp}
              iconStyle={cn("text-xl", currentVote === 1 && "text-green-500")}
            />
            <div className="text-l ml-1">{score}</div>
            <ButtonWithIcon
              onClick={handleDownVote}
              icon={FiArrowDown}
              iconStyle={cn("text-xl", currentVote === -1 && "text-red-500")}
            />
          </div>
          <div className="text-neutral-500 ml-8">
            <div className="comment-content mt-0">{comment?.content}</div>
            {comment?.isAI ? (
              <div className="mt-2 text-xs text-neutral-500">
                This comment was generated by our AI. It may not be accurate.
              </div>
            ) : (
              <div className="flex items-center mt-5 text-sm">
                <button className="cursor-pointer " onClick={() => {}}>
                  Reply
                </button>
              </div>
            )}
          </div>
        </div>

        {comment.childComments?.length > 0 && (
          <div className="pl-3">
            {comment.childComments.map((childComment: any) => (
              <CommentItem
                key={childComment.id}
                comment={childComment}
                authorId={authorId}
              />
            ))}
          </div>
        )}
      </li>
    </div>
  );
};
export default Comments;
